services:
  backend:
    build:
      context: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - ENV=prod

  frontend:
    build:
      context: ./MQR-frontend
        # In production, use the Dockerfile CMD to run the built app
    ports:
      - "3000:3000"
    
    environment:
      - HOST=0.0.0.0
    restart: always
