# Generated by Django 5.2.4 on 2025-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_handler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='refined_query',
        ),
        migrations.AddField(
            model_name='query',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
